using System;

namespace UnityEvents.Internal
{
	public struct QueuedEvent<T_Event> where T_Event : struct
	{
		public EventTarget target;
		public T_Event ev;

		public QueuedEvent(EventTarget target, T_Event ev)
		{
			this.target = target;
			this.ev = ev;
		}
	}

	public struct UnityEvent<T_Event> where T_Event : struct
	{
		public readonly T_Event ev;
		public readonly int subscriberIndex;

		public UnityEvent(T_Event ev, int subscriberIndex)
		{
			this.ev = ev;
			this.subscriberIndex = subscriberIndex;
		}
	}

	public struct EntityCallbackId<T_Event> : IEquatable<EntityCallbackId<T_Event>>
	{
		public EventTarget target;
		public Action<T_Event> callback;

		// Generated by Jetbrains
		private const int HASHCODE_MULTIPLIER = 397;

		public EntityCallbackId(EventTarget target, Action<T_Event> callback)
		{
			this.target = target;
			this.callback = callback;
		}

		public bool Equals(EntityCallbackId<T_Event> other)
		{
			return target.Equals(other.target) && Equals(callback, other.callback);
		}

		public override bool Equals(object obj)
		{
			if (ReferenceEquals(null, obj)) return false;
			return obj is EntityCallbackId<T_Event> other && Equals(other);
		}

		public override int GetHashCode()
		{
			unchecked
			{
				return (target.GetHashCode() * HASHCODE_MULTIPLIER) ^ (callback != null ? callback.GetHashCode() : 0);
			}
		}
	}}
